- hosts: registry
  gather_facts: no
  become: yes

  tasks:
    - ping:

    - name: deploy docker registry
      docker_container:
        name: '{{ registry_image }}_{{ registry_tag }}'
        image: '{{ registry_image }}:{{ registry_tag }}'
        state: present
        network_mode: host
#        ports: '{{ registry_ports }}'
        volumes: '{{ registry_volumes }}'
        restart_policy: on-failure
        restart_retries: 5
        env: '{{ registry_env }}'
