- hosts: docker
  gather_facts: no
  become: yes

  tasks:
    - name: stop and disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: install required packages
      yum:
        name: '{{ item }}'
        state: installed
        update_cache: yes
      with_items:
        - iptables-services

    - name: enable and restart iptables
      service:
        name: iptables
        state: restarted
        enabled: yes
# ------------------------------------------------------------------------------

- hosts: registry
  gather_facts: no
  become: yes

  roles:
    - docker-regictry-iptables-configure
# ------------------------------------------------------------------------------

- hosts: mongo
  gather_facts: no
  become: yes

  roles:
    - mongo-iptables-configure
# ------------------------------------------------------------------------------
