- hosts: mongo_shard
  gather_facts: no
  become: yes

  vars:
    container_state: started

  roles:
    - ping
    - mongo-shard-replica-change-state
# ------------------------------------------------------------------------------

- hosts: mongo_conf
  gather_facts: no
  become: yes

  vars:
    container_name: 'mongo_conf_{{ mongo_tag }}_{{ inventory_hostname }}'
    container_state: started

  roles:
    - ping
    - docker-container-change-state
# ------------------------------------------------------------------------------

- hosts: mongo_router
  gather_facts: no
  become: yes

  vars:
    container_name: 'mongo_router_{{ mongo_tag }}_{{ inventory_hostname }}'
    container_state: started

  roles:
    - ping
    - docker-container-change-state
# ------------------------------------------------------------------------------
