- hosts: mongo_shard
  gather_facts: no
  become: yes

  tasks:
    - ping:

    - name: present mongod (shards replicas) docker container
      docker_container:
        name: 'mongo_shard_{{ item }}_{{ mongo_tag }}_{{ inventory_hostname }}'
        image: '{{ mongo_image }}:{{ mongo_tag }}'
        state: present
        volumes: '/data/{{ item }}/db:/data/db'
        network_mode: host
#        ports:
#          - '{{ item }}:{{ item }}'
        restart_policy: on-failure
        restart_retries: 5
        env: '{{ mongo_shard_replica_env }}'
        command: 'mongod --port {{ item }} --shardsvr --replSet {{ item }}'
      with_items: '{{ mongo_shard_ports[:mongo_cluster_shards_count] }}'
# ------------------------------------------------------------------------------

- hosts: mongo_conf
  gather_facts: no
  become: yes

  tasks:
    - ping:

    - name: present mongod (configuration server) docker container
      docker_container:
        name: 'mongo_conf_{{ mongo_tag }}_{{ inventory_hostname }}'
        image: '{{ mongo_image }}:{{ mongo_tag }}'
        state: present
        volumes: '/data/{{ mongo_conf_replica_set_name }}/configdb:/data/configdb'
        network_mode: host
#        ports:
#         - '{{ mongo_conf_port }}:{{ mongo_conf_port }}'
        restart_policy: on-failure
        restart_retries: 5
        env: '{{ mongo_conf_env }}'
        command: mongod --config /etc/mongoc.conf
# ------------------------------------------------------------------------------

- hosts: mongo_router
  gather_facts: no
  become: yes

  tasks:
    - ping:

    - name: present mongos (router) docker container
      docker_container:
        name: 'mongo_router_{{ mongo_tag }}_{{ inventory_hostname }}'
        image: '{{ mongo_image }}:{{ mongo_tag }}'
        state: present
        volumes: '{{ mongo_router_volumes }}'
        network_mode: host
#        ports:
#         - '{{ mongo_router_port }}:{{ mongo_router_port }}'
        restart_policy: on-failure
        restart_retries: 5
        env: '{{ mongo_router_env }}'
        command: mongos --config /etc/mongos.conf
# ------------------------------------------------------------------------------
